name: LoveGame
description: A Flutter application for tracking tennis matches.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_inappwebview: ^6.0.0
  intl: ^0.20.2
  http: ^1.3.0
  path_provider: ^2.1.1
  flutter_svg: ^2.1.0
  html: ^0.15.4
  cached_network_image: ^3.4.1
  url_launcher: ^6.1.10
  transparent_image: ^2.0.1
  share_plus: ^7.0.0
  package_info_plus: ^4.0.0
  shared_preferences: ^2.2.0
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  liquid_glass_renderer: ^0.2.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/2025_atp_tournament.json
    - assets/2025_wta_tournament.json
    - assets/2026_atp_tournament.json
    - assets/2026_wta_tournament.json
    - assets/images/
    - assets/svg/
